name: Build PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Setup eden-api
      run: | 
        cd eden-api && mvn clean install
        cd ..

    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Patch Parchment
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git submodule update --init --recursive
        ./parchment jar

    - uses: actions/upload-artifact@v2
      with:
        name: Parchment-PR${{ github.event.pull_request.number }}-JDK${{ matrix.java }}
        path: parchment-paperclip.jar
