name: Build main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [21]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/jdks
            ~/.gradle/native
            ~/.gradle/wrapper
          key: ${{ runner.os }}-parchment-2-${{ hashFiles('**/*.gradle*', 'gradle/**', 'gradle.properties') }}
          restore-keys: ${{ runner.os }}-parchment-2

      - name: Patch Parchment
        env:
          ORG_GRADLE_PROJECT_edenSnapshotsUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_edenSnapshotsPassword: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches
          ./gradlew createMojmapBundlerJar
          ./gradlew :parchment-api:publishMavenPublicationToEdenSnapshotsRepository
          ./gradlew publishDevBundlePublicationToEdenSnapshotsRepository -PpublishDevBundle
        
      - uses: actions/upload-artifact@v3
        with:
          name: Parchment-JDK${{ matrix.java }}
          path: build/libs/parchment-paperclip-*.jar
